# Generated by Django 3.2.19 on 2023-09-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockist',
            old_name='in_stock',
            new_name='has_stock',
        ),
        migrations.RenameField(
            model_name='stockist',
            old_name='business_type',
            new_name='name',
        ),
    ]
